### ISSUE TITLE
SIGQUIT: exit signal does not handle properly

### ISSUE THREAD

**Issue by kmahyyg** [Finb/bark-server#198]
Service:
```
ExecStop=/bin/kill -s QUIT $MAINPID
```

Logs:

```
Feb 07 04:53:48 cngate bark-server[1093]: SIGQUIT: quit
Feb 07 04:53:48 cngate bark-server[1093]: PC=0x4659a1 m=0 sigcode=0
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 0 [idle]:
Feb 07 04:53:48 cngate bark-server[1093]: runtime.futex()
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/sys_linux_amd64.s:552 +0x21
Feb 07 04:53:48 cngate bark-server[1093]: runtime.futexsleep(0x0?, 0x0?, 0x1?)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/os_linux.go:66 +0x36
Feb 07 04:53:48 cngate bark-server[1093]: runtime.notesleep(0xf4b9c8)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/lock_futex.go:159 +0x87
Feb 07 04:53:48 cngate bark-server[1093]: runtime.mPark(...)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/proc.go:1449
Feb 07 04:53:48 cngate bark-server[1093]: runtime.stopm()
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/proc.go:2228 +0x8d
Feb 07 04:53:48 cngate bark-server[1093]: runtime.startlockedm(0xc00002c500?)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/proc.go:2451 +0x65
Feb 07 04:53:48 cngate bark-server[1093]: runtime.schedule()
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/proc.go:3222 +0x73
Feb 07 04:53:48 cngate bark-server[1093]: runtime.park_m(0xc0000036c0?)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/proc.go:3336 +0x14d
Feb 07 04:53:48 cngate bark-server[1093]: runtime.mcall()
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/asm_amd64.s:425 +0x43
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 1 [IO wait, 2 minutes]:
Feb 07 04:53:48 cngate bark-server[1093]: internal/poll.runtime_pollWait(0x7f5819235218, 0x72)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/netpoll.go:302 +0x89
Feb 07 04:53:48 cngate bark-server[1093]: internal/poll.(*pollDesc).wait(0xc0000c0880?, 0x1fffffffffff?, 0x0)
Feb 07 04:53:48 cngate bark-server[1093]:         internal/poll/fd_poll_runtime.go:83 +0x32
Feb 07 04:53:48 cngate bark-server[1093]: internal/poll.(*pollDesc).waitRead(...)
Feb 07 04:53:48 cngate bark-server[1093]:         internal/poll/fd_poll_runtime.go:88
Feb 07 04:53:48 cngate bark-server[1093]: internal/poll.(*FD).Accept(0xc0000c0880)
Feb 07 04:53:48 cngate bark-server[1093]:         internal/poll/fd_unix.go:614 +0x22c
Feb 07 04:53:48 cngate bark-server[1093]: net.(*netFD).accept(0xc0000c0880)
Feb 07 04:53:48 cngate bark-server[1093]:         net/fd_unix.go:172 +0x35
Feb 07 04:53:48 cngate bark-server[1093]: net.(*TCPListener).accept(0xc0002c5098)
Feb 07 04:53:48 cngate bark-server[1093]:         net/tcpsock_posix.go:139 +0x28
Feb 07 04:53:48 cngate bark-server[1093]: net.(*TCPListener).Accept(0xc0002c5098)
Feb 07 04:53:48 cngate bark-server[1093]:         net/tcpsock.go:288 +0x3d
Feb 07 04:53:48 cngate bark-server[1093]: github.com/valyala/fasthttp.acceptConn(0xc0000e0900, {0xb41340, 0xc0002c5098?}, 0xc000341808)
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/server.go:1883 +0x122
Feb 07 04:53:48 cngate bark-server[1093]: github.com/valyala/fasthttp.(*Server).Serve(0xc0000e0900, {0xb41340?, 0xc0002c5098})
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/server.go:1777 +0x4d4
Feb 07 04:53:48 cngate bark-server[1093]: github.com/gofiber/fiber/v2.(*App).Listen(0xc0000b2280, {0x7fffb344cf06?, 0x4?})
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/gofiber/fiber/v2@v2.36.0/listen.go:73 +0xd1
Feb 07 04:53:48 cngate bark-server[1093]: main.main.func1(0xc0000e0480?)
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/finb/bark-server/v2/main.go:203 +0x605
Feb 07 04:53:48 cngate bark-server[1093]: github.com/urfave/cli/v2.(*App).RunContext(0xc00024c1c0, {0xb41858?, 0xc0000aa000}, {0xc0000a8000, 0xc, 0xc})
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/urfave/cli/v2@v2.11.1/app.go:386 +0xe9f
Feb 07 04:53:48 cngate bark-server[1093]: github.com/urfave/cli/v2.(*App).Run(...)
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/urfave/cli/v2@v2.11.1/app.go:251
Feb 07 04:53:48 cngate bark-server[1093]: main.main()
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/finb/bark-server/v2/main.go:207 +0x11c5
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 19 [sleep]:
Feb 07 04:53:48 cngate bark-server[1093]: time.Sleep(0x1dcd6500)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/time.go:194 +0x12e
Feb 07 04:53:48 cngate bark-server[1093]: github.com/gofiber/fiber/v2/middleware/logger.New.func1()
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/gofiber/fiber/v2@v2.36.0/middleware/logger/logger.go:91 +0x75
Feb 07 04:53:48 cngate bark-server[1093]: created by github.com/gofiber/fiber/v2/middleware/logger.New
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/gofiber/fiber/v2@v2.36.0/middleware/logger/logger.go:89 +0x31b
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 20 [runnable]:
Feb 07 04:53:48 cngate bark-server[1093]: main.main.func1.2()
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/finb/bark-server/v2/main.go:188 +0xb9
Feb 07 04:53:48 cngate bark-server[1093]: created by main.main.func1
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/finb/bark-server/v2/main.go:185 +0x42a
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 21 [sleep]:
Feb 07 04:53:48 cngate bark-server[1093]: time.Sleep(0x2540be400)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/time.go:194 +0x12e
Feb 07 04:53:48 cngate bark-server[1093]: github.com/valyala/fasthttp.(*workerPool).Start.func2()
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/workerpool.go:67 +0x56
Feb 07 04:53:48 cngate bark-server[1093]: created by github.com/valyala/fasthttp.(*workerPool).Start
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/workerpool.go:59 +0xd9
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 7 [syscall]:
Feb 07 04:53:48 cngate bark-server[1093]: os/signal.signal_recv()
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/sigqueue.go:151 +0x2f
Feb 07 04:53:48 cngate bark-server[1093]: os/signal.loop()
Feb 07 04:53:48 cngate bark-server[1093]:         os/signal/signal_unix.go:23 +0x19
Feb 07 04:53:48 cngate bark-server[1093]: created by os/signal.Notify.func1.1
Feb 07 04:53:48 cngate bark-server[1093]:         os/signal/signal.go:151 +0x2a
Feb 07 04:53:48 cngate bark-server[1093]: goroutine 23 [sleep]:
Feb 07 04:53:48 cngate bark-server[1093]: time.Sleep(0x3b9aca00)
Feb 07 04:53:48 cngate bark-server[1093]:         runtime/time.go:194 +0x12e
Feb 07 04:53:48 cngate bark-server[1093]: github.com/valyala/fasthttp.updateServerDate.func1()
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/header.go:2102 +0x1e
Feb 07 04:53:48 cngate bark-server[1093]: created by github.com/valyala/fasthttp.updateServerDate
Feb 07 04:53:48 cngate bark-server[1093]:         github.com/valyala/fasthttp@v1.38.0/header.go:2100 +0x25
Feb 07 04:53:48 cngate bark-server[1093]: rax    0xca
Feb 07 04:53:48 cngate bark-server[1093]: rbx    0x0
Feb 07 04:53:48 cngate bark-server[1093]: rcx    0x4659a3
Feb 07 04:53:48 cngate bark-server[1093]: rdx    0x0
Feb 07 04:53:48 cngate bark-server[1093]: rdi    0xf4b9c8
Feb 07 04:53:48 cngate bark-server[1093]: rsi    0x80
Feb 07 04:53:48 cngate bark-server[1093]: rbp    0x7fffb344ca08
Feb 07 04:53:48 cngate bark-server[1093]: rsp    0x7fffb344c9c0
Feb 07 04:53:48 cngate bark-server[1093]: r8     0x0
Feb 07 04:53:48 cngate bark-server[1093]: r9     0x0
Feb 07 04:53:48 cngate bark-server[1093]: r10    0x0
Feb 07 04:53:48 cngate bark-server[1093]: r11    0x286
Feb 07 04:53:48 cngate bark-server[1093]: r12    0x7fffb344ca40
Feb 07 04:53:48 cngate bark-server[1093]: r13    0x0
Feb 07 04:53:48 cngate bark-server[1093]: r14    0xf4ad20
Feb 07 04:53:48 cngate bark-server[1093]: r15    0xffffffffffffffff
Feb 07 04:53:48 cngate bark-server[1093]: rip    0x4659a1
Feb 07 04:53:48 cngate bark-server[1093]: rflags 0x286
Feb 07 04:53:48 cngate bark-server[1093]: cs     0x33
Feb 07 04:53:48 cngate bark-server[1093]: fs     0x0
Feb 07 04:53:48 cngate bark-server[1093]: gs     0x0
Feb 07 04:53:48 cngate systemd[1]: bark-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 07 04:53:48 cngate systemd[1]: bark-server.service: Failed with result 'exit-code'.
```

**Comment by mritd** [comment]
It looks like you are using Systemd to stop bark-server? If you want to exit the program, please do not use the QUIT signal.

The QUIT signal is used to get the process core dump file, if you are debugging on mac you can refer to [https://nasa.github.io/trick/howto_guides/How-to-dump-core-file-on-MacOS.html](https://nasa.github.io/trick/howto_guides/How-to-dump-core-file-on-MacOS.html)

If you just want to stop the application, you don't need to set the ExecStop option, or you can use the SIGKILL signal.

[https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillSignal=](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillSignal=)

**Comment by kmahyyg** [comment]
ouch. now I understand. It seems that I have some misunderstanding of those signals. Thanks for your response.
